name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prep
      run: mkdir build && cd build
    - name: configure
      run: cmake ..
    - name: make
      run: cmake --build .
