name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: action-gtest
      uses: CyberZHG/github-action-gtest@0.0.1
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake .
    - name: build
      run: cmake --build .
    - name: test
      run: ctest --verbose

